
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

shell_command:
  obtener_precio_luz: python3 /config/scripts/precio_luz.py

command_line:
  - sensor:
      name: Precio Luz Texto
      command: "python3 /config/scripts/precio_luz.py"
      scan_interval: 60
      value_template: "{{ value | string | trim }}"

script:
  precio_luz_hoy:
    sequence:
      - delay: "00:00:02"
      - service: tts.speak
        target:
          entity_id: tts.google_translate_es_com
        data:
          media_player_entity_id: media_player.despacho
          message: "{{ states('sensor.precio_luz_texto') }}"
input_text:
  ultimo_periodo_luz:
    name: Ãšltimo periodo de luz
    initial: ""